-- Candidatos / CVs por local (texto OCR + campos estructurados; sin imagen).
CREATE TABLE IF NOT EXISTS candidates (
  id CHAR(36) NOT NULL,
  shopId CHAR(36) NOT NULL,
  firstName VARCHAR(120) NOT NULL,
  lastName VARCHAR(120) NOT NULL,
  email VARCHAR(180) NULL,
  phone VARCHAR(60) NULL,
  documentId VARCHAR(60) NULL,
  address VARCHAR(255) NULL,
  city VARCHAR(120) NULL,
  country VARCHAR(120) NULL,
  birthDate DATE NULL,
  nationality VARCHAR(120) NULL,
  linkedIn VARCHAR(255) NULL,
  website VARCHAR(255) NULL,
  summary TEXT NULL,
  education JSON NULL,
  experience JSON NULL,
  skills JSON NULL,
  languages JSON NULL,
  rawText LONGTEXT NULL,
  notes TEXT NULL,
  status ENUM('new', 'reviewing', 'hired', 'rejected') NOT NULL DEFAULT 'new',
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME(6) NULL ON UPDATE CURRENT_TIMESTAMP(6),
  deletedAt DATETIME(6) NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  KEY idx_candidates_shop (shopId),
  KEY idx_candidates_status (shopId, status),
  CONSTRAINT fk_candidates_shop FOREIGN KEY (shopId) REFERENCES shops (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
